name: Sync to GitLab

on:
  push:
    branches:
      - main

jobs:
  sync-to-gitlab:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Fetch all history for all tags and branches

      - name: Add GitLab remote
        run: git remote add gitlab https://oauth2:${{ secrets.GITLAB_ACCESS_TOKEN }}@gitlab.com/YeDaniel/github_actions_contest_aac_html.git

      - name: Push changes to GitLab
        run: |
            git push gitlab HEAD:main --force
